######################################################################
# Automatically generated by qmake (2.01a) Fri Jan 16 22:07:44 2009
######################################################################

TEMPLATE = subdirs
SUBDIRS += qxtbdbhash qxtbdbtree

test.CONFIG += recursive
QMAKE_EXTRA_TARGETS += test
