######################################################################
# Automatically generated by qmake (2.01a) Fri Jan 16 22:24:46 2009
######################################################################

TEMPLATE = subdirs
SUBDIRS += rpc

test.CONFIG += recursive
QMAKE_EXTRA_TARGETS += test
