######################################################################
# Automatically generated by qmake (2.01a) Mon Jan 26 19:28:11 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
CONFIG += qxt no_keywords
QXT = berkeley core crypto gui network sql web

# Input
SOURCES += main.cpp
