######################################################################
# Automatically generated by qmake (2.01a) Fri Jan 16 22:06:29 2009
######################################################################

TEMPLATE = subdirs
SUBDIRS += berkeley core crypto gui network sql # web
