######################################################################
# Automatically generated by qmake (2.01a) Fri Jan 16 22:06:29 2009
######################################################################

TEMPLATE = subdirs
SUBDIRS += other unit

test.depends += sub-unit
test.recurse += unit
test.CONFIG += recursive
QMAKE_EXTRA_TARGETS += test
