######################################################################
# Automatically generated by qmake (2.01a) Fri Jan 16 22:48:34 2009
######################################################################

TEMPLATE = subdirs
SUBDIRS += addressbook xmlstorage
