######################################################################
# Automatically generated by qmake (2.01a) Fri Jan 16 22:20:27 2009
######################################################################

TEMPLATE = subdirs
SUBDIRS += bind fifo filelock job pipe sharedprivate slotjob QxtFileLock
