######################################################################
# Automatically generated by qmake (2.01a) Tue Jan 20 22:15:59 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
CONFIG += qxt qtestlib
QXT = core
include(../../test.pri)

# Input
HEADERS += sender.h receiver.h
SOURCES += tst_qxtslotmapper.cpp
