######################################################################
# Automatically generated by qmake (2.01a) Fri Jan 16 22:25:31 2009
######################################################################

TEMPLATE = subdirs
# SUBDIRS += async cgi direct invoketest upload # TODO: fix these unit tests
SUBDIRS += htmltemplate

test.CONFIG += recursive
QMAKE_EXTRA_TARGETS += test
