######################################################################
# Automatically generated by qmake (2.01a) Fri Jan 16 22:24:22 2009
######################################################################

TEMPLATE = subdirs
SUBDIRS += unit

test.CONFIG += recursive
QMAKE_EXTRA_TARGETS += test
