######################################################################
# Automatically generated by qmake (2.01a) Fri Jan 16 22:47:44 2009
######################################################################

TEMPLATE = subdirs
SUBDIRS += berkeley displaysettings ircpeer qxtflowview # country web
