######################################################################
# Automatically generated by qmake (2.01a) Fri Jan 16 22:47:44 2009
######################################################################

TEMPLATE = subdirs
!win32:SUBDIRS += berkeley
SUBDIRS += ircpeer qxtflowview # country web
