######################################################################
# Automatically generated by qmake (2.01a) Fri Jan 30 20:15:53 2009
######################################################################

TEMPLATE = subdirs
SUBDIRS += app no_keywords QxtFileLock QxtScheduleView slotjob
