######################################################################
# Automatically generated by qmake (2.01a) Sun Mar 1 19:09:35 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
CONFIG += qxt
QXT += core gui

# Input
FORMS += displaysettingsdialog.ui
HEADERS += displaysettingsdialog.h
SOURCES += displaysettingsdialog.cpp main.cpp
