######################################################################
# Automatically generated by qmake (2.01a) Fri Jan 30 20:25:09 2009
######################################################################

test.depends = first
!isEmpty(DESTDIR):test.commands += cd $(DESTDIR) &&
unix {
    macx:test.commands += ./$(TARGET).app/Contents/MacOS/$(TARGET)
    else:test.commands += ./$(TARGET)
} else:win32 {
    test.CONFIG += recursive
    build_pass {
        test.commands += $(TARGET)
    }
}
QMAKE_EXTRA_TARGETS += test
