######################################################################
# Automatically generated by qmake (2.01a) Fri Jan 30 20:13:42 2009
######################################################################

TEMPLATE = subdirs
SUBDIRS += berkeley core crypto gui network sql # web

test.CONFIG += recursive
QMAKE_EXTRA_TARGETS += test
