######################################################################
# Automatically generated by qmake (2.01a) Fri Jan 30 20:13:42 2009
######################################################################

TEMPLATE = subdirs
contains(DEFINES,HAVE_DB):contains(QXT_MODULES, berkeley):SUBDIRS += berkeley
contains(QXT_MODULES, core):SUBDIRS += core
contains(QXT_MODULES, gui):SUBDIRS += gui
contains(QXT_MODULES, network):SUBDIRS += network
contains(QXT_MODULES, sql):SUBDIRS += sql
contains(QXT_MODULES, web):SUBDIRS += web
#contains(DEFINES,HAVE_ZEROCONF):contains(QXT_MODULES, zeroconf):SUBDIRS += zeroconf

test.CONFIG += recursive
QMAKE_EXTRA_TARGETS += test
