######################################################################
# Automatically generated by qmake (2.01a) Tue Feb 13 23:13:40 2007
######################################################################

TEMPLATE = app
DESTDIR = .
TARGET = QxtCursesTest

# Input
SOURCES += cursestest.cpp
HEADERS += cursestest.h
CONFIG += qxt
QXT += curses core kit
